name: deploy to S3
on: 
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: S3 sync
        run: aws s3 sync . s3://izmyuta-homepage --delete --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers --exclude "README.md"
